version: '3'
services:
    mongodb-standalone:
        image: percona/percona-server-mongodb
        container_name: mongodb-standalone
        ports:
            - "27017:27017"
        volumes:
            - "./volume/sample:/home/sample/" 
        command: mongod --auth --storageEngine wiredTiger  
    rs1r1:
        image: percona/percona-server-mongodb
        container_name: rs1r1
        ports:
            - "27040:27040"
        volumes:
            - "./volume/sample:/home/sample/"     
        command: mongod --port 27040 --replSet rs1 --storageEngine wiredTiger 
    rs1r2:
        image: percona/percona-server-mongodb
        container_name: rs1r2
        ports:
            - "27041:27041"
        volumes:
            - "./volume/sample:/home/sample/" 
        command: mongod --port 27041 --replSet rs1 --storageEngine wiredTiger 
    rs1r3:
        image: percona/percona-server-mongodb
        container_name: rs1r3
        ports:
            - "27042:27042"
        volumes:
            - "./volume/sample:/home/sample/" 
        command: mongod --port 27042 --replSet rs1 --storageEngine wiredTiger 
    rs2r1:
        image: percona/percona-server-mongodb
        container_name: rs2r1
        ports:
            - "27050:27050"
        volumes:
            - "./volume/sample:/home/sample/"     
        command: mongod --port 27050 --replSet rs2 --storageEngine wiredTiger 
    rs2r2:
        image: percona/percona-server-mongodb
        container_name: rs2r2
        ports:
            - "27051:27051"
        volumes:
            - "./volume/sample:/home/sample/" 
        command: mongod --port 27051 --replSet rs2 --storageEngine wiredTiger 
    rs2r3:
        image: percona/percona-server-mongodb
        container_name: rs2r3
        ports:
            - "27052:27052"
        volumes:
            - "./volume/sample:/home/sample/" 
        command: mongod --port 27052 --replSet rs2 --storageEngine wiredTiger 
    config1:
        image: percona/percona-server-mongodb
        container_name: config1
        ports:
            - "27030:27030"
        volumes:
            - "./volume/data/configdb1:/data/configdb"
        command: mongod --configsvr --replSet cfg --port 27030 
    config2:
        image: percona/percona-server-mongodb
        container_name: config2
        ports:
            - "27031:27031"
        volumes:
            - "./volume/data/configdb2:/data/configdb"    
        command: mongod --configsvr --replSet cfg --port 27031 
    config3:
        image: percona/percona-server-mongodb
        container_name: config3
        ports:
            - "27032:27032"
        volumes:
            - "./volume/data/configdb3:/data/configdb"
        command: mongod --configsvr --replSet cfg --port 27032 
    mongos1:
        image: percona/percona-server-mongodb
        container_name: mongos1
        ports:
            - "27060:27017"
        depends_on:
          - config1
          - config2
          - config3
        command: mongos --configdb cfg/config1:27030,config2:27031,config3:27032 --port 27017 --bind_ip_all
    mongos2:
        image: percona/percona-server-mongodb
        container_name: mongos2
        ports:
            - "27061:27017"
        depends_on:
          - config1
          - config2
          - config3
        command: mongos --configdb cfg/config1:27030,config2:27031,config3:27032 --port 27017 --bind_ip_all

