version: '3'
services:
    mongodb-standalone:
        image: percona/percona-server-mongodb
        container_name: mongodb-standalone
        ports:
            - "27017:27017"
        volumes:
            - "./volume/dbshell:/home/mongodb/.dbshell" 
        command: mongod --storageEngine wiredTiger  
